# Generated by Django 4.1.4 on 2023-03-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_full_name_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User'},
        ),
    ]
