# Generated by Django 4.1.4 on 2023-03-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customar', '0002_ticket_total_seat_buyer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_info',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
